/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(bbheader_source.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(ba67ce8aac48bc08d693abbe705901e3)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <dvbs2/bbheader_source.h>
// pydoc.h is automatically generated in the build directory
#include <bbheader_source_pydoc.h>

void bind_bbheader_source(py::module& m)
{

    using bbheader_source    = ::gr::dvbs2::bbheader_source;


    py::class_<bbheader_source, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<bbheader_source>>(m, "bbheader_source", D(bbheader_source))

        .def(py::init(&bbheader_source::make),
           py::arg("nstreams"),
           py::arg("framesize1"),
           py::arg("rate1"),
           py::arg("constellation1"),
           py::arg("pilots1"),
           py::arg("goldcode1"),
           py::arg("mac_address1"),
           py::arg("framesize2"),
           py::arg("rate2"),
           py::arg("constellation2"),
           py::arg("pilots2"),
           py::arg("goldcode2"),
           py::arg("mac_address2"),
           py::arg("framesize3"),
           py::arg("rate3"),
           py::arg("constellation3"),
           py::arg("pilots3"),
           py::arg("goldcode3"),
           py::arg("mac_address3"),
           py::arg("framesize4"),
           py::arg("rate4"),
           py::arg("constellation4"),
           py::arg("pilots4"),
           py::arg("goldcode4"),
           py::arg("mac_address4"),
           py::arg("rolloff"),
           py::arg("ping_reply"),
           py::arg("ipaddr_spoof"),
           py::arg("dst_address"),
           D(bbheader_source,make)
        )
        



        ;




}







