/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(bbheader_bb.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(439064e8d6afd54220829f465df812b0)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <dvbs2/bbheader_bb.h>
// pydoc.h is automatically generated in the build directory
#include <bbheader_bb_pydoc.h>

void bind_bbheader_bb(py::module& m)
{

    using bbheader_bb    = ::gr::dvbs2::bbheader_bb;


    py::class_<bbheader_bb, gr::block, gr::basic_block,
        std::shared_ptr<bbheader_bb>>(m, "bbheader_bb", D(bbheader_bb))

        .def(py::init(&bbheader_bb::make),
           py::arg("nstreams"),
           py::arg("framesize1"),
           py::arg("rate1"),
           py::arg("constellation1"),
           py::arg("pilots1"),
           py::arg("goldcode1"),
           py::arg("framesize2"),
           py::arg("rate2"),
           py::arg("constellation2"),
           py::arg("pilots2"),
           py::arg("goldcode2"),
           py::arg("framesize3"),
           py::arg("rate3"),
           py::arg("constellation3"),
           py::arg("pilots3"),
           py::arg("goldcode3"),
           py::arg("framesize4"),
           py::arg("rate4"),
           py::arg("constellation4"),
           py::arg("pilots4"),
           py::arg("goldcode4"),
           py::arg("rolloff"),
           D(bbheader_bb,make)
        )
        



        ;




}







