/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(bbscrambler_bb.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(7282d70db8a8a469b6e8ba6c36903248)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <dvbs2/bbscrambler_bb.h>
// pydoc.h is automatically generated in the build directory
#include <bbscrambler_bb_pydoc.h>

void bind_bbscrambler_bb(py::module& m)
{

    using bbscrambler_bb    = ::gr::dvbs2::bbscrambler_bb;


    py::class_<bbscrambler_bb, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<bbscrambler_bb>>(m, "bbscrambler_bb", D(bbscrambler_bb))

        .def(py::init(&bbscrambler_bb::make),
           D(bbscrambler_bb,make)
        )
        



        ;




}







